### ISSUE TITLE
Merge conflicts with spec master

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/sign-extension-ops#5]
There are a few merge conflicts between this repo and the spec master branch:
```
CONFLICT (content): Merge conflict in document/core/syntax/instructions.rst
[...]
CONFLICT (content): Merge conflict in document/core/appendix/index-instructions.rst
```
This prevents the [testsuite mirror](https://github.com/WebAssembly/testsuite)'s update script from updating the sign-extension-ops tests.

**Comment by sbc100** [comment]
Can someone take a look at this?  @rossberg , @binji ?
